### ISSUE TITLE
This is not a "Discord bot in every language".

### ISSUE THREAD

**Issue by RaidAndFade** [Cyber28/Freeman#8]
This is a discord bot, that compiles and runs every hello world file that you've already created. *this is a discord bot made in JS*, that runs commands that you've already defined.

**Comment by LizardDoesStuff** [comment]
PREACH

**Comment by GagePielsticker** [comment]
BLESS UP

**Comment by Cyber28** [comment]
Where does it even say it's a "Discord bot in every language"?

**Comment by RaidAndFade** [comment]
https://github.com/Cyber28/Freeman/blob/master/README.md

> Discord bot made in as many languages as possible

**Comment by Cyber28** [comment]
Yeah, not every. The point is for the bot to *use* as many languages as possible

**Comment by RaidAndFade** [comment]
This is a discord bot made in python
